using 'main.bicep'

/*
AVD Deployment / Network Parameters

Environment:
- poc

Used by:
- infra/modules/network/main.bicep

Notes:
- Resource names are generated by shared naming rules.
- Address spaces must be approved through network/IPAM before deployment.
- Hub peering values must match the enterprise hub network design.
- Leave hub peering values empty until the hub VNet resource ID is known.
- Do not store secrets, credentials, private keys, or certificate material in this file.
*/

// Environment

param environment = 'poc'
param location = 'eastus'

// Virtual Network

param virtualNetworkAddressPrefixes = [
  '10.243.192.0/24'
]

// Subnets

param sessionHostSubnets = [
  {
    purpose: 'opsPooled'
    addressPrefix: '10.243.192.0/27'
  }
  {
    purpose: 'opsPersonal'
    addressPrefix: '10.243.192.32/27'
  }
  {
    purpose: 'devPersonal'
    addressPrefix: '10.243.192.64/27'
  }
  {
    purpose: 'devPooled'
    addressPrefix: '10.243.192.96/27'
  }
]

param privateEndpointSubnet = {
  purpose: 'privateEndpoints'
  addressPrefix: '10.243.192.128/27'
}

// Reserved address space:
// - 10.243.192.160/27 - Future AzureBastionSubnet or management subnet
// - 10.243.192.192/26 - Future expansion

// DNS

// Leave empty unless domain DNS servers are required for AD DS or hybrid join.
param dnsServers = [
  '10.113.20.3'
  '10.113.20.4'
  '172.16.28.10'
]
