using 'main.bicep'

/*
AVD Deployment / Network Parameters

Environment:
- poc

Used by:
- infra/modules/network/main.bicep

Notes:
- Resource names are generated by shared naming rules.
- Address spaces must be approved through network/IPAM before deployment.
- Hub peering values must match the enterprise hub network design.
- Leave hub peering values empty until the hub VNet resource ID is known.
- Do not store secrets, credentials, private keys, or certificate material in this file.
*/

// Environment

param environment = 'poc'
param location = 'eastus'

// Virtual Network

param virtualNetworkAddressPrefixes = [
  '10.243.192.0/24'
]

// Subnets

param sessionHostSubnetAddressPrefix = '10.243.192.0/27'
param privateEndpointSubnetAddressPrefix = '10.243.192.32/27'

// DNS

// Leave empty unless domain DNS servers are required for AD DS or hybrid join.
param dnsServers = [
  '10.113.20.3'
  '10.113.20.4'
  '172.16.28.10'
]

// Hub Peering

param hubVirtualNetworkResourceId = '/subscriptions/3cea8964-57d2-44c4-9c10-0c10866165c8/resourceGroups/networkvpn-rg-prod/providers/Microsoft.Network/virtualNetworks/hub-vnet-prod'
param hubSubscriptionId = '3cea8964-57d2-44c4-9c10-0c10866165c8'
param hubResourceGroupName = 'networkvpn-rg-prod'
param hubVirtualNetworkName = 'hub-vnet-prod'
param skipHubToSpokePeering = false
