using 'main.bicep'

/*
AVD Deployment / Storage Parameters

Environment:
- poc

Used by:
- infra/modules/storage/main.bicep

Notes:
- Resource names are generated by shared naming rules.
- FSLogix storage account naming is location-aware.
- Group object IDs must be Microsoft Entra group object IDs, not display names.
- Do not store secrets, credentials, private keys, or certificate material in this file.
*/

// Environment

param environment = 'poc'
param location = 'eastus'

// FSLogix Storage

param fslogixShareName = 'profiles'
param fslogixShareQuotaGiB = 1024
param storageAccountSkuName = 'Premium_LRS'

// Storage Auth

param deployStorageAuth = true

// User groups
// AVD user groups that need standard FSLogix profile share access.
param avdUserGroupObjectIds = [
  '1cc07c58-29fd-4b99-98df-b36e3cd9a7ae'
  'aa09d144-a544-4cc9-b0bc-ff053061445c'
  'ebdf4719-7e5e-4b65-89a5-2a7d24627f75'
]

// Admin groups
// Admin/operator groups that can manage FSLogix share ACLs.
param avdAdminGroupObjectIds = [
  '53422f94-8888-496a-b3b8-18e062da591c'
]


// Temporary for testing of POC deployments individual modules:

param privateEndpointSubnetResourceId = '/subscriptions/b908e3b2-448e-4a3f-9d79-996703913a99/resourceGroups/tv-avd-rg-network-eus-poc/providers/Microsoft.Network/virtualNetworks/tv-avd-vnet-pri-eus-poc/subnets/tv-avd-snet-private-endpoints-eus-poc'

param filePrivateDnsZoneResourceId = '/subscriptions/b908e3b2-448e-4a3f-9d79-996703913a99/resourceGroups/tv-avd-rg-network-eus-poc/providers/Microsoft.Network/privateDnsZones/privatelink.file.core.windows.net'

param deployDiagnosticSettings = true
