using 'main.bicep'

/*
AVD Deployment / Compute Parameters

Environment:
- poc

Used by:
- infra/modules/compute/main.bicep

Notes:
- Deploys initial session host virtual machines.
- Domain join credentials must be supplied securely by the pipeline.
- AVD registration tokens must be generated by the pipeline and passed as secure deployment parameters.
- Do not store secrets, credentials, private keys, or certificate material in this file.
*/

param environment = 'poc'

/*
param domainFqdn = 'truevalue.com'
param domainOuPath = 'OU=AVD,OU=Servers,DC=truevalue,DC=com'
*/

// for debuggin purposes.
param deploySessionHosts = false

param sessionHostGroups = [
  {
    name: 'opsPooled'
    resourceGroupPurpose: 'opsPooled'
    hostPoolPurpose: 'opsPooled'
    vmNamePrefix: 'tvavdops'
    vmCount: 1
    vmSize: 'Standard_E16as_v5'
    osDisk: {
      storageAccountType: 'Premium_LRS'
      diskSizeGB: 128
    }
  }
  {
    name: 'devPersonal'
    resourceGroupPurpose: 'devPersonal'
    hostPoolPurpose: 'devPersonal'
    vmNamePrefix: 'tvavddp'
    vmCount: 1
    vmSize: 'Standard_D8als_v6'
    osDisk: {
      storageAccountType: 'Premium_LRS'
      diskSizeGB: 256
    }
  }
  {
    name: 'devPooled'
    resourceGroupPurpose: 'devPooled'
    hostPoolPurpose: 'devPooled'
    vmNamePrefix: 'tvavddv'
    vmCount: 1
    vmSize: 'Standard_D8as_v5'
    osDisk: {
      storageAccountType: 'Premium_LRS'
      diskSizeGB: 256
    }
  }
]
