using 'main.bicep'

/*
AVD Deployment / Service Objects Parameters

Environment:
- poc

Used by:
- infra/modules/serviceobjects/main.bicep

Notes:
- Host pool, desktop application group, and workspace names are logical configuration names.
- Azure resource names are generated by the shared naming functions in the Bicep module.
- RBAC principal IDs must reference approved Microsoft Entra groups for AVD user access.
- Do not store secrets, credentials, private keys, or certificate material in this file.
*/

// Imports
import {
  avdDefaults
  avdRoleDefinitionIds
} from '../../shared/config.bicep'

// Parameters

// Deployment environment key used to select shared environment configuration.
param environment = 'poc'

// Workspace configurations deployed for the POC Service Objects module.
param workspaces = [
  {
    name: 'primary'
    friendlyName: 'True Value AVD POC'
    description: 'Primary Azure Virtual Desktop workspace for the POC environment.'
    publicNetworkAccess: 'Disabled'
  }
]

// Host pool configurations, including each desktop application group and AVD user RBAC assignments.
param hostPools = [
  {
    name: 'opsPooled'
    friendlyName: 'True Value AVD POC Ops Pooled'
    description: 'Pooled AVD host pool for Ops users.'
    hostPoolType: 'Pooled'
    loadBalancerType: 'DepthFirst'
    preferredAppGroupType: 'Desktop'
    maxSessionLimit: 10
    validationEnvironment: false
    startVMOnConnect: true
    customRdpProperty: avdDefaults.customRdpProperty
    publicNetworkAccess: 'Disabled'
    desktopApplicationGroup: {
      name: 'opsPooledDesktop'
      friendlyName: 'True Value AVD POC Ops Desktop'
      description: 'Desktop application group for Ops pooled users.'
      workspaceName: 'primary'
      rbacAssignments: [
        {
          // Grants desktop access to the Operations pooled host pool.
          // Principal: AVD Operations Pooled Users security group.
          principalId: 'aa09d144-a544-4cc9-b0bc-ff053061445c'
          principalType: 'Group'
          roleDefinitionId: avdRoleDefinitionIds.desktopVirtualizationUser
        }
      ]
    }
  }
  {
    name: 'devPooled'
    friendlyName: 'True Value AVD POC Dev Pooled'
    description: 'Pooled AVD host pool for Dev users.'
    hostPoolType: 'Pooled'
    loadBalancerType: 'DepthFirst'
    preferredAppGroupType: 'Desktop'
    maxSessionLimit: 10
    validationEnvironment: false
    startVMOnConnect: false
    customRdpProperty: avdDefaults.customRdpProperty
    publicNetworkAccess: 'Disabled'
    desktopApplicationGroup: {
      name: 'devPooledDesktop'
      friendlyName: 'True Value AVD POC Dev Pooled Desktop'
      description: 'Desktop application group for Dev pooled users.'
      workspaceName: 'primary'
      rbacAssignments: [
        {
          principalId: 'aa09d144-a544-4cc9-b0bc-ff053061445c'
          principalType: 'Group'
          roleDefinitionId: avdRoleDefinitionIds.desktopVirtualizationUser
        }
      ]
    }
  }
  {
    name: 'devPersonal'
    friendlyName: 'True Value AVD POC Dev Personal'
    description: 'Personal AVD host pool for Dev users.'
    hostPoolType: 'Personal'
    loadBalancerType: 'Persistent'
    preferredAppGroupType: 'Desktop'
    maxSessionLimit: 1
    validationEnvironment: false
    startVMOnConnect: false
    customRdpProperty: avdDefaults.customRdpProperty
    publicNetworkAccess: 'Disabled'
    desktopApplicationGroup: {
      name: 'devPersonalDesktop'
      friendlyName: 'True Value AVD POC Dev Personal Desktop'
      description: 'Desktop application group for Dev personal desktops.'
      workspaceName: 'primary'
      rbacAssignments: [
        {
          principalId: 'ebdf4719-7e5e-4b65-89a5-2a7d24627f75'
          principalType: 'Group'
          roleDefinitionId: avdRoleDefinitionIds.desktopVirtualizationUser
        }
      ]
    }
  }
]
