name: poc-bicep-$(workloadName)-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra/**
      - scripts/**
      - pipelines/**
    exclude:
      - docs/**

pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/**
      - scripts/**
      - pipelines/**
    exclude:
      - docs/**

variables:
  workloadName: avd
  environmentName: poc
  azureServiceConnection: tv-avd-core-poc
  deploymentLocation: eastus

pool:
  vmImage: ubuntu-latest

stages:
  - template: templates/bicep-deployment-template.yml
    parameters:
      azureServiceConnection: tv-avd-core-poc
      environmentName: poc
      workloadName: avd
      deploymentScope: Subscription
      deploymentLocation: eastus
      templateFile: '$(Build.SourcesDirectory)/infra/modules/bootstrap/bootstrap.bicep'
      parameterFile: '$(Build.SourcesDirectory)/infra/modules/bootstrap/poc.bicepparam'
      validationLevel: Provider
      whatIfResultFormat: FullResourcePayloads
