name: poc-bicep-$(workloadName)-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra/**
      - scripts/**
      - pipelines/**
    exclude:
      - docs/**

pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/**
      - scripts/**
      - pipelines/**
    exclude:
      - docs/**

variables:
  workloadName: avd
  environmentName: poc
  azureServiceConnection: tv-avd-poc-deploy-sc
  deploymentLocation: eastus

pool:
  vmImage: ubuntu-latest

stages:
  - template: templates/bicep-deployment-template.yml
    parameters:
      deploymentUnitName: bootstrap
      azureServiceConnection: tv-avd-poc-deploy-sc
      environmentName: poc
      workloadName: avd
      deploymentScope: Subscription
      deploymentLocation: eastus
      templateFile: '$(Build.SourcesDirectory)/infra/modules/bootstrap/main.bicep'
      parameterFile: '$(Build.SourcesDirectory)/infra/modules/bootstrap/poc.bicepparam'
      validationLevel: Provider
      whatIfResultFormat: FullResourcePayloads

  - template: templates/bicep-deployment-template.yml
    parameters:
      deploymentUnitName: controlplane
      dependsOn:
        - Deploy_bootstrap
      azureServiceConnection: tv-avd-poc-deploy-sc
      environmentName: poc
      workloadName: avd-controlplane
      deploymentScope: Subscription
      deploymentLocation: eastus
      templateFile: '$(Build.SourcesDirectory)/infra/modules/controlplane/main.bicep'
      parameterFile: '$(Build.SourcesDirectory)/infra/modules/controlplane/poc.bicepparam'
      validationLevel: Provider
      whatIfResultFormat: FullResourcePayloads
