name: shared-bicep-$(workloadName)-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra/modules/sharedresources/**
      - infra/shared/**
      - scripts/**
      - pipelines/templates/**
      - pipelines/azure-pipelines-shared.yml
    exclude:
      - docs/**
      - infra/modules/bootstrap/**
      - infra/modules/service-objects/**
      - infra/modules/network/**
      - infra/modules/storage/**
      - infra/modules/compute/**

pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/modules/sharedresources/**
      - infra/shared/**
      - scripts/**
      - pipelines/templates/**
      - pipelines/azure-pipelines-shared.yml
    exclude:
      - docs/**
      - infra/modules/bootstrap/**
      - infra/modules/service-objects/**
      - infra/modules/network/**
      - infra/modules/storage/**
      - infra/modules/compute/**

variables:
  workloadName: avd
  environmentName: shared
  avdDevOpsEnvironment: shared-avd
  azureServiceConnection: tv-avd-poc-deploy-sc
  avdSharedResourcesServiceConnection: tv-avd-shared-deploy-sc
  avdNetworkPeeringServiceConnection: tv-avd-network-peering-sc
  azureLocation: eastus

Pool:
  vmImage: ubuntu-latest

stages:
  - template: templates/bicep-deployment-template.yml
    parameters:
      deploymentUnitName: sharedresources
      azureDevOpsEnvironment: $(avdDevOpsEnvironment)
      azureServiceConnection: $(avdSharedResourcesServiceConnection)
      environmentName: shared
      workloadName: $(workloadName)-sharedresources
      deploymentScope: Subscription
      deploymentLocation: $(azureLocation)
      templateFile: "$(Build.SourcesDirectory)/infra/modules/sharedresources/main.bicep"
      parameterFile: "$(Build.SourcesDirectory)/infra/modules/sharedresources/poc.bicepparam"
      validationLevel: Provider
      whatIfResultFormat: FullResourcePayloads
