name: dev-bicep-$(workloadName)-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra/**
      - scripts/**
      - pipelines/**
    exclude:
      - docs/**

pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/**
      - scripts/**
      - pipelines/**
    exclude:
      - docs/**

variables:
  workloadName: <workload-name>

pool:
  vmImage: ubuntu-latest

stages:
  - template: templates/bicep-deployment-template.yml
    parameters:
      azureServiceConnection: '<dev-service-connection-name>'
      environmentName: dev
      workloadName: $(workloadName)
      resourceGroupName: '<dev-resource-group-name>'
      validationLevel: Provider
      whatIfResultFormat: FullResourcePayloads