using 'main.bicep'

/*
AVD Deployment / Service Objects Parameters

Environment:
- poc

Used by:
- infra/modules/service-objects/main.bicep

Notes:
- Host pool, desktop application group, and workspace names are logical configuration names.
- Azure resource names are generated by the shared naming functions in the Bicep module.
- RBAC principal IDs must reference approved Microsoft Entra groups for AVD user access.
- Do not store secrets, credentials, private keys, or certificate material in this file.
*/

// Imports

import {
  avdRdpPropertyPresets
  resourceDefaults
  roleDefinitionIds
} from '../../shared/config.bicep'

// Parameters

// Deployment environment key used to select shared environment configuration.
param environment = 'poc'

// Azure region for service object resources.
param location = 'eastus'

// Workspace configurations deployed for the POC Service Objects module.
param workspaces = [
  {
    name: 'primary'
    friendlyName: 'True Value AVD POC'
    description: 'Primary Azure Virtual Desktop workspace for the POC environment.'
    publicNetworkAccess: resourceDefaults.publicNetworkAccess
  }
]

// Host pool configurations, including each desktop application group and AVD user RBAC assignments.
param hostPools = [
  {
    name: 'opsPooled'
    friendlyName: 'True Value AVD POC Ops Pooled'
    description: 'Pooled AVD host pool for Ops users.'
    hostPoolType: 'Pooled'
    loadBalancerType: 'DepthFirst'
    preferredAppGroupType: 'Desktop'
    maxSessionLimit: 10
    validationEnvironment: false
    startVMOnConnect: true
    customRdpProperty: avdRdpPropertyPresets.defaultSecure
    publicNetworkAccess: resourceDefaults.publicNetworkAccess
    desktopApplicationGroup: {
      name: 'opsPooledDesktop'
      friendlyName: 'True Value AVD POC Ops Desktop'
      description: 'Desktop application group for Ops pooled users.'
      workspaceName: 'primary'
      rbacAssignments: [
        {
          // Grants desktop access to the Operations pooled host pool.
          // Principal: AVD Operations Pooled Users security group.
          principalId: 'aa09d144-a544-4cc9-b0bc-ff053061445c'
          principalType: 'Group'
          roleDefinitionId: roleDefinitionIds.avd.desktopVirtualizationUser
        }
      ]
    }
  }
  {
    name: 'devPooled'
    friendlyName: 'True Value AVD POC Dev Pooled'
    description: 'Pooled AVD host pool for Dev users.'
    hostPoolType: 'Pooled'
    loadBalancerType: 'DepthFirst'
    preferredAppGroupType: 'Desktop'
    maxSessionLimit: 10
    validationEnvironment: false
    startVMOnConnect: false
    customRdpProperty: avdRdpPropertyPresets.defaultSecure
    publicNetworkAccess: resourceDefaults.publicNetworkAccess
    desktopApplicationGroup: {
      name: 'devPooledDesktop'
      friendlyName: 'True Value AVD POC Dev Pooled Desktop'
      description: 'Desktop application group for Dev pooled users.'
      workspaceName: 'primary'
      rbacAssignments: [
        {
          principalId: 'aa09d144-a544-4cc9-b0bc-ff053061445c'
          principalType: 'Group'
          roleDefinitionId: roleDefinitionIds.avd.desktopVirtualizationUser
        }
      ]
    }
  }
  {
    name: 'devPersonal'
    friendlyName: 'True Value AVD POC Dev Personal'
    description: 'Personal AVD host pool for Dev users.'
    hostPoolType: 'Personal'
    loadBalancerType: 'Persistent'
    preferredAppGroupType: 'Desktop'
    maxSessionLimit: 1
    validationEnvironment: false
    startVMOnConnect: false
    customRdpProperty: avdRdpPropertyPresets.defaultSecure
    publicNetworkAccess: resourceDefaults.publicNetworkAccess
    desktopApplicationGroup: {
      name: 'devPersonalDesktop'
      friendlyName: 'True Value AVD POC Dev Personal Desktop'
      description: 'Desktop application group for Dev personal desktops.'
      workspaceName: 'primary'
      rbacAssignments: [
        {
          principalId: 'ebdf4719-7e5e-4b65-89a5-2a7d24627f75'
          principalType: 'Group'
          roleDefinitionId: roleDefinitionIds.avd.desktopVirtualizationUser
        }
      ]
    }
  }
]

param deployAutoscaleRbac = true

// Object ID of the Azure Virtual Desktop service principal in the True Value tenant.
// Get this with:
// az ad sp list --display-name "Azure Virtual Desktop" --query "[].{displayName:displayName, appId:appId, id:id}" -o table
param avdAutoscaleServicePrincipalObjectId = '9cdead84-a844-4324-93f2-b2e6bb768d07'

param scalingPlans = [
  {
    name: 'pooledAutoscale'
    friendlyName: 'True Value AVD POC Pooled Autoscale'
    description: 'Power management autoscale plan for pooled AVD host pools in the POC environment.'
    hostPoolType: 'Pooled'
    timeZone: 'Central Standard Time'
    exclusionTag: 'excludeFromScaling'
    hostPoolNames: [
      'opsPooled'
      'devPooled'
    ]
    schedules: [
      {
        name: 'weekdays'
        daysOfWeek: [
          'Monday'
          'Tuesday'
          'Wednesday'
          'Thursday'
          'Friday'
        ]

        rampUpStartTime: {
          hour: 6
          minute: 0
        }
        rampUpLoadBalancingAlgorithm: 'DepthFirst'
        rampUpMinimumHostsPct: 50
        rampUpCapacityThresholdPct: 70

        peakStartTime: {
          hour: 8
          minute: 0
        }
        peakLoadBalancingAlgorithm: 'DepthFirst'

        rampDownStartTime: {
          hour: 18
          minute: 0
        }
        rampDownLoadBalancingAlgorithm: 'DepthFirst'
        rampDownMinimumHostsPct: 10
        rampDownCapacityThresholdPct: 90
        rampDownWaitTimeMinutes: 30
        rampDownForceLogoffUsers: false
        rampDownStopHostsWhen: 'ZeroSessions'
        rampDownNotificationMessage: 'Your AVD session host may be shut down after active sessions end.'

        offPeakStartTime: {
          hour: 22
          minute: 0
        }
        offPeakLoadBalancingAlgorithm: 'DepthFirst'
      }
      {
        name: 'weekends'
        daysOfWeek: [
          'Saturday'
          'Sunday'
        ]

        rampUpStartTime: {
          hour: 8
          minute: 0
        }
        rampUpLoadBalancingAlgorithm: 'DepthFirst'
        rampUpMinimumHostsPct: 10
        rampUpCapacityThresholdPct: 80

        peakStartTime: {
          hour: 10
          minute: 0
        }
        peakLoadBalancingAlgorithm: 'DepthFirst'

        rampDownStartTime: {
          hour: 16
          minute: 0
        }
        rampDownLoadBalancingAlgorithm: 'DepthFirst'
        rampDownMinimumHostsPct: 0
        rampDownCapacityThresholdPct: 90
        rampDownWaitTimeMinutes: 30
        rampDownForceLogoffUsers: false
        rampDownStopHostsWhen: 'ZeroSessions'
        rampDownNotificationMessage: 'Your AVD session host may be shut down after active sessions end.'

        offPeakStartTime: {
          hour: 18
          minute: 0
        }
        offPeakLoadBalancingAlgorithm: 'DepthFirst'
      }
    ]
  }
]
